# Generated by Django 4.1.2 on 2023-06-15 02:22

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=100)),
                ('descripcionCategoria', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Categoria de productos',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('apellidoUsuario', models.CharField(max_length=60)),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('emailUsuario', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('telefonoUsuario', models.CharField(blank=True, max_length=10)),
                ('rolUsuario', models.CharField(choices=[('Em', 'Emprendedor'), ('Cl', 'Cliente')], max_length=80)),
            ],
            options={
                'verbose_name': 'Usuario registrado',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigodeBarras', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('descripcionProducto', models.TextField(max_length=1000)),
                ('imagenProducto', models.ImageField(default='Image_Default.jpeg', upload_to='')),
                ('precioUnitario', models.PositiveIntegerField()),
                ('cantidadProducto', models.IntegerField(default=0)),
                ('id_Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurnowDjango.categoria')),
            ],
            options={
                'verbose_name': 'Producto de Turnow',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('id_Emprendedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEmprendimiento', models.CharField(default='--', max_length=100)),
                ('descripcionEmp', models.TextField(max_length=1000)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('redSocialEmp', models.URLField(blank=True, null=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurnowDjango.usuario')),
            ],
            options={
                'verbose_name': 'Emprendedor registrado',
                'verbose_name_plural': 'Emprendedores',
                'db_table': 'Emprendedor',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(default='--', max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurnowDjango.usuario')),
            ],
            options={
                'verbose_name': 'Cliente registrado',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
    ]
