# Generated by Django 4.2.1 on 2023-05-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=100)),
                ('descripcionCategoria', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Categoria de productos',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('id_Emprendedor', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionEmp', models.TextField(max_length=1000)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('redSocialEmp', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'Emprendedor registrado',
                'verbose_name_plural': 'Emprendedors',
                'db_table': 'Emprendedor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('apellidoUsuario', models.CharField(max_length=60)),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('emailUsuario', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('telefonoUsuario', models.CharField(blank=True, max_length=10)),
                ('rolUsuario', models.CharField(choices=[('Em', 'Emprendedor'), ('Cl', 'Cliente')], max_length=80)),
            ],
            options={
                'verbose_name': 'Usuario registrado',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigodeBarras', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('descripcionProducto', models.TextField(max_length=1000)),
                ('precioUnitario', models.PositiveIntegerField()),
                ('cantidadProducto', models.IntegerField(default=0)),
                ('emprendedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurnowDjango.emprendedor')),
                ('id_Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurnowDjango.categoria')),
            ],
            options={
                'verbose_name': 'Producto de Turnow',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurnowDjango.usuario'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurnowDjango.usuario')),
            ],
            options={
                'verbose_name': 'Cliente registrado',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
    ]
