# Generated by Django 4.1.2 on 2023-06-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurnowDjango', '0002_carritocompras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritocompras',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='pago',
            field=models.CharField(default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='producto',
            field=models.ManyToManyField(related_name='carrito_producto', to='TurnowDjango.producto'),
        ),
        migrations.AlterModelTable(
            name='carritocompras',
            table='carrito',
        ),
    ]
