# Generated by Django 4.1.2 on 2023-06-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurnowDjango', '0004_remove_carritocompras_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompras',
            name='pago',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=80),
        ),
    ]
